---
- name: "Install packages"
  package:
    name:
      - jq
      - pipx
      - curl
      - seclists
      - penelope
      - rlwrap
      - ligolo-ng
      - feroxbuster
    state: latest
  become: true
  become_method: sudo

