---
- name: "Install scripts"
  copy:
    src: "{{ role_path }}/files/start"
    dest: "/usr/local/bin/start"
    owner: root
    group: root
    mode: '0755'
  become: true
  become_method: sudo

- name: "Install references"
  block:
    - name: "Create ref directory if it does not exist"
      file:
        path: "{{ ansible_facts['env']['HOME'] }}/ref"
        state: directory
        mode: '0755'

    - name: "Copy reference files"
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "{{ ansible_facts['env']['HOME'] }}/ref/{{ item }}"
      loop:
        - "adref.txt"
        - "breachref.txt"
        - "bloodref.txt"
        - "venomref.txt"
        - "dllref.txt"
        - "commonref.txt"
        - "breakoutref.txt"

    - name: "Configure user-specific bash aliases"
      ansible.builtin.blockinfile:
        path: "~/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED ALIASES"
        create: yes
        mode: '0644'
        block: |
          alias adref='cat {{ ansible_facts['env']['HOME'] }}/ref/adref.txt'
          alias breachref='cat {{ ansible_facts['env']['HOME'] }}/ref/breachref.txt'
          alias bloodref='cat {{ ansible_facts['env']['HOME'] }}/ref/bloodref.txt'
          alias venomref='cat {{ ansible_facts['env']['HOME'] }}/ref/venomref.txt'
          alias dllref='cat {{ ansible_facts['env']['HOME'] }}/ref/dllref.txt'
          alias commonref='cat {{ ansible_facts['env']['HOME'] }}/ref/commonref.txt'
          alias breakoutref='cat {{ ansible_facts['env']['HOME'] }}/ref/breakoutref.txt'
          alias ll='ls -la'
