#!/bin/bash

if [ -z "$1" ]; then
    echo "Please include a project name."
    echo "Usage: start <project_name>"
    exit 1
fi

PROJECT_NAME="$1"

if [ ! -d "$PROJECT_NAME" ]; then
    mkdir "$PROJECT_NAME"
else
    echo "Directory '$PROJECT_NAME' already exists. Exiting without changes."
    exit 1
fi

mkdir "$PROJECT_NAME/loot"
mkdir "$PROJECT_NAME/vulns"
touch "$PROJECT_NAME/users.txt"
touch "$PROJECT_NAME/passwords.txt"
touch "$PROJECT_NAME/creds.txt"
touch "$PROJECT_NAME/test.txt"
echo "Hello World" > "$PROJECT_NAME/test.txt"

if [ -n "$TMUX" ]; then
    exit 1
else
    tmux new-session -s "$PROJECT_NAME" -c "$(pwd)/$PROJECT_NAME"
fi
